apiVersion: v1
entries:
  cmsocial:
  - apiVersion: v2
    appVersion: v3
    created: "2022-03-15T19:48:05.450171766Z"
    dependencies:
    - name: cms
      repository: https://edomora97.github.io/cms/helm/
      version: 0.0.4
    description: A web application that builds a social coding platform upon CMS
    digest: b9fbdd8b3fcb2a088abe908a76f08e9a60ad0dd74678f359df7449554b9fba70
    name: cmsocial
    type: application
    urls:
    - cmsocial-0.0.1.tgz
    version: 0.0.1
generated: "2022-03-15T19:48:05.448177941Z"
